version: "3"
services:
  vote-project:
    image: abdalrahman1/votetracker-app:1.0
    container_name: vote-tracker-app
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV = ${NODE_ENV}
      - MONGO_URL_DEV=${MONGO_URL_DEV}
      - MONGO_URL_PROD=${MONGO_URL_PROD}
      - HOST=${HOST}
      - PORT=${PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_TIME=${RERESH_TOKEN_TIME}
      - COOKIE_EXPIRE=${COOKIE_EXPIRE}
    volumes:
      - vote-app:/app
      - /app/node_modules
    # networks:
    #   - my-network
    depends_on:
      - redis

  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_volume:/data
  #   networks:
  #     - my-network

volumes:
  vote-app:
  # redis_volume:

# networks:
#   my-network: