version: "3"
services:
  vote-project:
    image: abdalrahman1/votetracker-app:1.0
    build: .
    ports:
      - "1337:1337"
    # env_file:
    #   - .env
    volumes:
      - vote-app:/app
      - /app/node_modules

volumes:
  vote-app:
