name: Deploy Node Application 

on: 
  push: 
    branches: 
      - main
      - feature-app

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker-compose build 
      - name: Publish Image to docker hub
        run: docker push abdalrahman1/votetracker-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull abdalrahman1/votetracker-app:latest
      - name: Run Docker Container 
        run: docker-compose 